Repository owncloud/docs-client-android, pull requests merged in 2021-09, with the labels that each got.

#1 Add missing page aliases
  modules/ROOT/pages/appendices/release_notes.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation

#2 [2.18] [PR 1] Add missing page aliases
  modules/ROOT/pages/appendices/release_notes.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#3 Name typo fix
  antora.yml
Labels: bug

#4 [2.18] [PR 3] Name typo fix
  antora.yml
Labels: backport

#6 Update release notes
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: documentation

#7 [2.18] [PR 6] Update release notes
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: backport
