Repository owncloud/docs-client-android, pull requests merged in 2021-11, with the labels that each got.

#11 Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: deployment

#12 [2.18] [PR 11] Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: backport

#13 Fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/installation.adoc
Labels: bug

#14 [2.18] [PR 13] Fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/installation.adoc
Labels: backport

#15 New Android version
  site.yml
Labels: deployment

#16 [2.19] [PR 15] New Android version
  site.yml
Labels: backport

#18 antora.yml fix for 2.19
  antora.yml
Labels: deployment

#19 log, camera and scoped storage
  modules/ROOT/assets/images/logs/log-viewer-opened.png
  modules/ROOT/assets/images/logs/no-log-reading-app-found.png
  modules/ROOT/assets/images/logs/select-log-reading-app.png
  modules/ROOT/assets/images/logs/show-logs-list.png
  modules/ROOT/assets/images/logs/show-logs.png
  modules/ROOT/assets/images/settings/android-settings-camera-upload.png
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installation.adoc
  modules/ROOT/pages/settings.adoc
Labels: documentation

#20 [2.19] [PR 19] log, camera and scoped storage
  modules/ROOT/assets/images/logs/log-viewer-opened.png
  modules/ROOT/assets/images/logs/no-log-reading-app-found.png
  modules/ROOT/assets/images/logs/select-log-reading-app.png
  modules/ROOT/assets/images/logs/show-logs-list.png
  modules/ROOT/assets/images/logs/show-logs.png
  modules/ROOT/assets/images/settings/android-settings-camera-upload.png
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/installation.adoc
  modules/ROOT/pages/settings.adoc
Labels: backport

#21 Fix drone.star for master and 2.19
  .drone.star
Labels: deployment

#22 [2.19] [PR 21] Fix drone.star for master and 2.19
  .drone.star
Labels: backport

#23 Correct the pdf branch
  .drone.star
Labels: deployment
