Repository owncloud/docs-client-android, pull requests merged in 2022-03, with the labels that each got.

#75 Setting the description attribute
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/document_provider.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation.adoc
  modules/ROOT/pages/settings.adoc
Labels: deployment

#76 [2.20] [PR 75] Setting the description attribute
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/document_provider.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation.adoc
  modules/ROOT/pages/settings.adoc
Labels: backport

#77 [2.19] [PR 75] Setting the description attribute
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/connecting.adoc
  modules/ROOT/pages/document_provider.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation.adoc
  modules/ROOT/pages/settings.adoc
Labels: backport

#78 description fix
  modules/ROOT/pages/index.adoc
Labels: documentation

#79 [2.20] [PR 78] description fix
  modules/ROOT/pages/index.adoc
Labels: backport

#80 [2.19] [PR 78] description fix
  modules/ROOT/pages/index.adoc
Labels: backport
