Repository owncloud/docs-client-android, pull requests merged in 2024-01, with the labels that each got.

#156 Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: deployment, dependencies

#159 [4.0] [PR 156] Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#158 [4.1] [PR 156] Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#160 Just a small internal link fix
  docs/new-version-branch.md
Labels: documentation

#161 [4.0] [PR 160] Just a small internal link fix
  docs/new-version-branch.md
Labels: backport

#162 [4.1] [PR 160] Just a small internal link fix
  docs/new-version-branch.md
Labels: backport
